name: CI

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}

      - name: go to correctdir
        run: cd packages/website-analyzer-wc

      - name: List files in the repository aftere cd
        run: |
          ls ${{ github.workspace }}

      - name: Install dependencies
        run: pnpm install

      - name: Run CI
        run: pnpm run build
